# Generated by Django 5.2.3 on 2025-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="Введите почту", max_length=254, unique=True, verbose_name="Email"),
                ),
                ("full_name", models.CharField(help_text="Введите Ф.И.О.", max_length=255, verbose_name="Ф.И.О.")),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Добавьте комментарий", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
