# Generated by Django 5.2.3 on 2025-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(help_text="Введите тему", max_length=255, verbose_name="Тема письма")),
                ("body", models.TextField(help_text="Введите текст сообщения", verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
    ]
