# Generated by Django 5.2.3 on 2025-06-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "beginning_sending",
                    models.DateTimeField(
                        help_text="Укажите время в формате ГГГГ-ММ-ДД ЧЧ:ММ:СС", verbose_name="Начало рассылки"
                    ),
                ),
                (
                    "end_sending",
                    models.DateTimeField(
                        help_text="Укажите время в формате ГГГГ-ММ-ДД ЧЧ:ММ:СС", verbose_name="Конец рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("finished", "Завершена")],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="mailing.message"
                    ),
                ),
                ("subscriber", models.ManyToManyField(related_name="subscribers", to="mailing.subscriber")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-beginning_sending"],
            },
        ),
    ]
