# Generated by Django 5.2.3 on 2025-06-15 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailingmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingmodel",
            name="beginning_sending",
            field=models.DateTimeField(
                help_text="Укажите время в формате ДД.ММ.ГГГГ ЧЧ:ММ:СС", verbose_name="Начало рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="end_sending",
            field=models.DateTimeField(
                help_text="Укажите время в формате ДД.ММ.ГГГГ ЧЧ:ММ:СС", verbose_name="Конец рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="subscriber",
            field=models.ManyToManyField(
                help_text="Удерживайте “Control“ (или “Command“ на Mac), чтобы выбрать несколько значений.",
                related_name="subscribers",
                to="mailing.subscriber",
                verbose_name="Получатель рассылки",
            ),
        ),
    ]
