# Generated by Django 5.2.3 on 2025-06-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailingmodel_beginning_sending_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_and_time", models.DateTimeField(auto_now_add=True, verbose_name="Время отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("successfully", "Успешно"), ("not_successful", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус отправки",
                    ),
                ),
                ("server_mail_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mailings", to="mailing.mailingmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["-date_and_time"],
            },
        ),
    ]
