# Generated by Django 5.2.3 on 2025-06-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_mailingmodel_options_mailingmodel_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["date_and_time"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingmodel",
            options={
                "ordering": ["beginning_sending"],
                "permissions": [
                    ("can_disable_mailing", "Can disable mailing"),
                    ("can_send_message", "Can send_message"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
